package belajarjavahani;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author giaaa
 */
public class Tugasmodul10 extends javax.swing.JFrame {

    /**
     * Creates new form latihanmodul10
     */
    public Tugasmodul10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eHasil = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        LuasKelilingSegitiga = new javax.swing.JMenu();
        LuasS = new javax.swing.JMenuItem();
        LuasdanKelilingPP = new javax.swing.JMenu();
        LuasdanKelilinggPP = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        LuasdanKelilingLingkaran = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data1");

        jLabel2.setText("Data2");

        jLabel8.setText("Menghitung");

        jLabel9.setText("Hasil");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Proses");
        jMenu6.add(jSeparator2);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Bersih");
        jMenu6.add(jCheckBoxMenuItem2);

        LuasKelilingSegitiga.setText("Segitiga");

        LuasS.setText("Luas dan Keliling");
        LuasS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasSActionPerformed(evt);
            }
        });
        LuasKelilingSegitiga.add(LuasS);

        jMenu6.add(LuasKelilingSegitiga);

        LuasdanKelilingPP.setText("Persegi Panjang");

        LuasdanKelilinggPP.setText("Luas dan Keliling");
        LuasdanKelilinggPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasdanKelilinggPPActionPerformed(evt);
            }
        });
        LuasdanKelilingPP.add(LuasdanKelilinggPP);

        jMenu6.add(LuasdanKelilingPP);

        jMenu10.setText("Lingkaran");

        LuasdanKelilingLingkaran.setText("Luas dan Keliling");
        LuasdanKelilingLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasdanKelilingLingkaranActionPerformed(evt);
            }
        });
        jMenu10.add(LuasdanKelilingLingkaran);

        jMenu6.add(jMenu10);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Bantuan");
        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eData1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(eData2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LuasdanKelilinggPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasdanKelilinggPPActionPerformed

        // Ambil data dari input
int panjang = Integer.parseInt(eData1.getText());
int lebar = Integer.parseInt(eData2.getText());

// Hitung Luas Persegi Panjang
int luas = panjang * lebar;

// Hitung Keliling Persegi Panjang
int keliling = 2 * (panjang + lebar);

// Tampilkan hasil
eHasil.setText("Luas: " + luas + "\nKeliling: " + keliling);

    }//GEN-LAST:event_LuasdanKelilinggPPActionPerformed

    private void LuasSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasSActionPerformed
        // TODO Luas dan Keliling SEGITIGA:
int alas = Integer.parseInt(eData1.getText());
int tinggi = Integer.parseInt(eData2.getText());

// Hitung Luas Segitiga
int luas = (alas * tinggi) / 2;

// Hitung sisi miring (asumsi segitiga siku-siku)
double sisiMiring = Math.sqrt(alas * alas + tinggi * tinggi);

// Hitung Keliling Segitiga
double keliling = alas + tinggi + sisiMiring;

// Tampilkan hasil
eHasil.setText("Luas: " + luas + "\nKeliling: " + keliling);

        
    }//GEN-LAST:event_LuasSActionPerformed

    private void LuasdanKelilingLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasdanKelilingLingkaranActionPerformed
        // TODO add your handling code here:
        // Ambil data dari input
int jariJari = Integer.parseInt(eData1.getText());

// Hitung Luas Lingkaran
double luas = Math.PI * jariJari * jariJari;

// Hitung Keliling Lingkaran
double keliling = 2 * Math.PI * jariJari;

// Tampilkan hasil
eHasil.setText("Luas: " + luas + "\nKeliling: " + keliling);

    }//GEN-LAST:event_LuasdanKelilingLingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugasmodul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugasmodul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugasmodul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugasmodul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugasmodul10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu LuasKelilingSegitiga;
    private javax.swing.JMenuItem LuasS;
    private javax.swing.JMenuItem LuasdanKelilingLingkaran;
    private javax.swing.JMenu LuasdanKelilingPP;
    private javax.swing.JMenuItem LuasdanKelilinggPP;
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eHasil;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
