/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasmodul13;

import javax.swing.JOptionPane;
import com.mysql.cj.jdbc.Driver;
import java.awt.HeadlessException;
import java.sql.*;
import java.time.Clock;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author giaaa
 */
public class ekskulsiswa extends javax.swing.JFrame {

    /**
     * Creates new form ekskulsiswa
     */
    public ekskulsiswa() {
        initComponents();
        tampildata(); //memanggil fungsi menampilkan data
        bersih(); //memanggil fungsi membersihkan text field
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cboEskul = new javax.swing.JComboBox<>();
        cboJurusan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelEskulsiswa = new javax.swing.JTable();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nim");

        jLabel2.setText("Nama");

        jLabel3.setText("Ekstrakulikuler");

        jLabel4.setText("Jurusan");

        cboEskul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PMR", "PASKIBRA", "PRAMUKA", "ROHIS", "SILAT", "BASKET", "VOLI", "FUTSAL", "PADUS", "GAADA" }));

        cboJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PPLG", "TJKT", "TPFL", "TKRO" }));

        jButton1.setText("tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("tampil semua");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cari");

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        tabelEskulsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelEskulsiswa.setShowGrid(true);
        tabelEskulsiswa.setSurrendersFocusOnKeystroke(true);
        tabelEskulsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelEskulsiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelEskulsiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(29, 29, 29)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNim)
                                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboEskul, 0, 109, Short.MAX_VALUE)
                                            .addComponent(cboJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(93, 93, 93))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboEskul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nim = txtNim.getText();
        String nama = txtNama.getText();
        String jurusan = (String) cboJurusan.getSelectedItem();
        String eskul = (String) cboEskul.getSelectedItem();

        // Validasi: Pastikan semua field diisi
        if (nim.isEmpty() || nama.isEmpty() || jurusan == null || jurusan.isEmpty() || eskul == null || eskul.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi lengkap datanya!");
        } else {
            try {
                Connection conn = tugasmodul13.koneksi.GetConnection();
                String sql = "INSERT INTO latihanmodul13 (nim, nama, jurusan,eskul) VALUES (?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, nim);
                pstmt.setString(2, nama);
                pstmt.setString(3, jurusan);
                pstmt.setString(4, eskul);
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                tampildata(); // Refresh tabel
                bersih(); // Bersihkan form
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = tabelEskulsiswa.getSelectedRow();
        if (row >= 0) { // Memeriksa jika ada baris yang dipilih
            String nim = (String) tabelEskulsiswa.getValueAt(row, 0);
            String nama = txtNama.getText();
            String jurusan = (String) cboJurusan.getSelectedItem();
            String Eskul = (String) cboEskul.getSelectedItem();

            try {
                Connection conn = tugasmodul13.koneksi.GetConnection();
                String sql = "UPDATE latihanmodul13 SET nama = ?, jurusan = ?, eskul = ? WHERE nim = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, nama);
                pstmt.setString(2, jurusan);
                pstmt.setString(3, Eskul); // Perbaiki urutan parameter
                pstmt.setString(4, nim);   // Nim sebagai parameter terakhir

                pstmt.executeUpdate();

                // Menampilkan data terbaru di tabel
                tampildata();
                bersih();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal mengupdate data: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diedit");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelEskulsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelEskulsiswaMouseClicked
        // TODO add your handling code here:
        int row = tabelEskulsiswa.getSelectedRow();
        if (row >= 0) { // Memastikan ada baris yang dipilih
            txtNim.setText((String) tabelEskulsiswa.getValueAt(row, 0));
            txtNama.setText((String) tabelEskulsiswa.getValueAt(row, 1));
            cboJurusan.setSelectedItem((String) tabelEskulsiswa.getValueAt(row, 2));
            cboEskul.setSelectedItem((String) tabelEskulsiswa.getValueAt(row, 3));
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diedit");
        }
    }//GEN-LAST:event_tabelEskulsiswaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String nim = txtNim.getText();
        if (nim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi NIM yang akan dihapus!");
            return;
        }
        try {
            Connection conn = tugasmodul13.koneksi.GetConnection();
            String sql = "DELETE FROM latihanmodul13 WHERE nim = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nim);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampildata(); // Refresh tabel
            bersih(); // Bersihkan form
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
        String cari = txtCari.getText();
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NIM");
        tbl.addColumn("Nama");
        tbl.addColumn("Jurusan");
        tbl.addColumn("eskul");
        tabelEskulsiswa.setModel(tbl);
        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery(
                    "SELECT * FROM latihanmodul13 WHERE nim LIKE '%" + cari + "%' "
                    + "OR nama LIKE '%" + cari + "%' "
                    + "OR jurusan LIKE '%" + cari + "%' "
                    + "OR eskul LIKE '%" + cari + "%';"
            );

            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("jurusan"),
                    res.getString("eskul"),});
                tabelEskulsiswa.setModel(tbl);
                bersih();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "salah");
        }
    }//GEN-LAST:event_txtCariActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("NIM");
    tbl.addColumn("Nama");
    tbl.addColumn("Jurusan");
    tbl.addColumn("Eskul");
    tabelEskulsiswa.setModel(tbl);

    try {
        Connection connection = tugasmodul13.koneksi.GetConnection();
        Statement statement = connection.createStatement();
        ResultSet res = statement.executeQuery("SELECT * FROM latihanmodul13 ORDER BY nama ASC");

        while (res.next()) {
            tbl.addRow(new Object[]{
                res.getString("nim"),
                res.getString("nama"),
                res.getString("jurusan"),
                res.getString("eskul")
            });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(rootPane, "Salah: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ekskulsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ekskulsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ekskulsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ekskulsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ekskulsiswa().setVisible(true);
            }
        });
    }

    public void bersih() {
        txtNim.setText("");
        txtNama.setText("");
        txtCari.setText("");
        cboJurusan.setSelectedIndex(0);
        cboEskul.setSelectedIndex(0);
    }

    public void tampildata() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NIM");
        tbl.addColumn("Nama");
        tbl.addColumn("Jurusan");
        tbl.addColumn("Eskul");
        tabelEskulsiswa.setModel(tbl);
        try {
            Connection connection = tugasmodul13.koneksi.GetConnection();
            if (connection != null) {
                System.out.println("Koneksi berhasil!");
            } else {
                System.out.println("Koneksi gagal!");
            }
            Statement statement = connection.createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM latihanmodul13 ORDER BY nama ASC");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("jurusan"),
                    res.getString("eskul")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Salah: " + e.getMessage());
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboEskul;
    private javax.swing.JComboBox<String> cboJurusan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tabelEskulsiswa;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
